services:
  fitlog-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: fitlog_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fitlog-api:
    build: ./fitlog-api
    restart: always
    environment:
      #Adicionar quando for aplicar novas migrations no banco
      # - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    depends_on:
      - fitlog-db

  fitlog-web:
    build: ./fitlog-web
    ports:
      - "3000:5173"
    volumes:
      - ./fitlog-web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080/api
    depends_on:
      - fitlog-api
